[build-system]
requires = ["setuptools","wheel","pysatellite","numpy","matplotlib","tf-agents[reverb]","reverb","tensorflow","pandas",
            "filterpy"]
build-backend = "setuptools.build_meta"
